import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,readdirSync,statSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os'; import {join} from 'node:path';
import {DemoGateway,GatewayError,runBoundedCycle,status,validateCandidate,validateCandidatePackage,evaluateCandidateQuality,QUALITY_README_HEADINGS,validateOpportunity,validateReview,acquireLock,CURATED_SEEDS,reconcileCuratedSeeds,MAX_GENERATION_ATTEMPTS} from '../packages/factory/dist/index.js';
import {canonicalOpportunityKey} from '../packages/factory/dist/opportunity.js';
const cfg=(d,e={})=>({baseUrl:'https://gateway.test/demo',origin:'https://origin.test',projectId:'github-pages',model:'demo-auto',dailyTokenBudget:1e6,minRemainingForCall:10000,stateDir:d,...e});
const response=(s,b)=>new Response(JSON.stringify(b),{status:s,headers:{'content-type':'application/json'}});
const opportunity=(id,title=id)=>({id,slug:id,title,category:'documentation',problem:'A bounded data problem.',successCriteria:'Produces deterministic read-only output.',source:'curated',createdAt:'2026-01-01T00:00:00.000Z'});
const qualityReadme='# Reference\n\n'+QUALITY_README_HEADINGS.map((h,i)=>h+'\n'+(('Concrete evidence-first reference guidance for bounded read-only analysis, with explicit observations, assumptions, unknowns, and verification steps. ').repeat(i===2?3:2))).join('\n\n');
const pkg=(name='safe-cap',extra={})=>({schema:'acr/candidate-package/v0.1',name,version:'0.1.0',description:'Read only reference content.',category:'documentation',tags:['documentation','reference'],permissions:{network:false,filesystem:false,database:false,shell:false},files:[{path:'README.md',content:qualityReadme},{path:'evals/cases.json',content:JSON.stringify([{id:'normal',input:{value:1},expected:{value:1}},{id:'missing',input:{},expected:{unknown:true}},{id:'edge',input:{value:null},expected:{bounded:true}}])}],...extra});
const gateway=(packageName='safe-cap')=>({chat:async(_p,p)=>p==='proposal'?{content:JSON.stringify(pkg(packageName)),usage:{total_tokens:12}}:p==='review'?{content:'{"decision":"PASS","reasons":[]}',usage:{total_tokens:8}}:{content:'{"opportunities":[]}',usage:{total_tokens:4}}});

test('gateway preserves 401 refresh and maps 429/403',async()=>{let sessions=0;const secret='do-not-log-token';const g=new DemoGateway(cfg('/tmp/x'),async(url,init)=>{if(url.endsWith('/session')){sessions++;return response(200,{dmo_token:secret})}if(sessions===1)return response(401,{});assert.equal(JSON.parse(init.body).stream,false);return response(200,{choices:[{message:{content:'{}'}}],usage:{total_tokens:7}})});assert.equal((await g.chat('x','review')).usage.total_tokens,7);assert.equal(sessions,2);for(const code of [429,403])await assert.rejects(()=>new DemoGateway(cfg('/tmp/x'),async()=>response(code,{})).chat('x','proposal'),new RegExp(code===429?'rate_limited':'configuration_blocked'))});
test('strict opportunity validation rejects extras and invalid fields',()=>{const o=opportunity('safe-id');assert.equal(validateOpportunity(o),true);assert.equal(validateOpportunity({...o,extra:true}),false);assert.equal(validateOpportunity({...o,id:'Bad ID'}),false);assert.equal(validateOpportunity({...o,category:'unsafe'}),false)});
test('opportunity canonical key catches title duplicates across IDs',()=>assert.equal(canonicalOpportunityKey(opportunity('a','Same title')),canonicalOpportunityKey(opportunity('b',' same title '))));
test('candidate quality gate enforces depth sections and eval coverage',()=>{const good=pkg();assert.deepEqual(evaluateCandidateQuality(good),{status:'PASS',reasons:[]});const shallow={...good,files:[{path:'README.md',content:'# Tiny'},{path:'evals/cases.json',content:JSON.stringify([{id:'one',input:{},expected:{}}])}]};const q=evaluateCandidateQuality(shallow);assert.equal(q.status,'FAIL');assert(q.reasons.includes('readme_too_shallow'));assert(q.reasons.includes('too_few_eval_cases'));assert(q.reasons.some(x=>x.startsWith('missing_')));});
test('candidate package validator is structural and adversarial',()=>{const good=pkg();assert.equal(validateCandidatePackage(good),true);for(const bad of [{...good,unknown:true},{...good,permissions:{...good.permissions,shell:true}},{...good,files:[...good.files,{path:'run.sh',content:'x'}]},{...good,files:[{path:'README.md',content:'x'},{path:'evals/cases.json',content:'[{"id":"x","input":{},"expected":{},"extra":1}]'}]},{...good,files:[{path:'README.md',content:'x'},{path:'evals/cases.json',content:'not json'}]},{...good,files:[{path:'README.md',content:'x'},{path:'evals/cases.json',content:'[]'}]}])assert.equal(validateCandidatePackage(bad),false)});
test('legacy validateCandidate remains strict and review limit is preserved',()=>{const old={name:'x',description:'x',permissions:{network:false,filesystem:false},files:['README.md']};assert.equal(validateCandidate(old),true);assert.equal(validateCandidate({...old,script:'x'}),false);assert.equal(validateCandidate({...old,files:['../x.md']}),false);assert.equal(validateReview({decision:'PASS',reasons:Array(21).fill('x')}),false);assert.equal(validateReview({decision:'PASS',reasons:[],extra:1}),false)});
test('offline cycle materializes strict package and records usage',async()=>{const d=mkdtempSync(join(tmpdir(),'acr-'));const r=await runBoundedCycle(cfg(d),gateway(),[opportunity('one')]);assert.equal(r.status,'candidate_saved');assert.equal(readFileSync(join(d,'candidates.jsonl'),'utf8').split('\n').filter(Boolean).length,1);assert.equal(statSync(r.candidatePath).mode&0o777,0o700);assert.match(readFileSync(join(d,'budget.jsonl'),'utf8'),/"total_tokens":12/)});
test('old metadata-only proposals retry bounded times then consume',async()=>{const d=mkdtempSync(join(tmpdir(),'acr-'));const g={chat:async(_p,p)=>p==='proposal'?{content:'{"name":"old","description":"metadata","permissions":{"network":false,"filesystem":false},"files":["README.md"]}',usage:{total_tokens:1}}:p==='discover'?{content:'{"opportunities":[]}',usage:{total_tokens:1}}:{content:'{}',usage:{total_tokens:1}}};for(let i=0;i<MAX_GENERATION_ATTEMPTS;i++)assert.equal((await runBoundedCycle(cfg(d),g,[opportunity('one')])).status,'unsafe_candidate');assert.equal((await runBoundedCycle(cfg(d),g,[opportunity('one')])).status,'discovery_empty');});
test('review failure retries bounded times and transient failure retries',async()=>{const d=mkdtempSync(join(tmpdir(),'acr-'));const fail={chat:async(_p,p)=>p==='proposal'?{content:JSON.stringify(pkg()),usage:{total_tokens:1}}:p==='review'?{content:'{"decision":"FAIL","reasons":["no"]}',usage:{total_tokens:1}}:{content:'{"opportunities":[]}',usage:{total_tokens:1}}};for(let i=0;i<MAX_GENERATION_ATTEMPTS;i++)assert.equal((await runBoundedCycle(cfg(d),fail,[opportunity('one')])).status,'review_failed');assert.equal((await runBoundedCycle(cfg(d),fail,[opportunity('one')])).status,'discovery_empty');const d2=mkdtempSync(join(tmpdir(),'acr-'));let n=0;const transient={chat:async()=>{n++;throw new GatewayError('transient_503')}};assert.equal((await runBoundedCycle(cfg(d2,{}),transient,[opportunity('one')])).status,'transient_failure');assert.equal((await runBoundedCycle(cfg(d2,{}),gateway(),[opportunity('one')])).status,'candidate_saved');});
test('legacy seedId records are consumed and status counts them',async()=>{const d=mkdtempSync(join(tmpdir(),'acr-'));writeFileSync(join(d,'opportunities.jsonl'),[opportunity('a'),opportunity('b'),opportunity('c')].map(JSON.stringify).join('\n')+'\n');writeFileSync(join(d,'candidates.jsonl'),JSON.stringify({seedId:'a',status:'CANDIDATE_ONLY'})+'\n');assert.equal(status(cfg(d)).queuedOpportunities,2);assert.equal((await runBoundedCycle(cfg(d),gateway(),[opportunity('a'),opportunity('b'),opportunity('c')])).opportunityId,'b')});
test('discovery refills after three seeds and dedupes id slug title within batch/history',async()=>{const d=mkdtempSync(join(tmpdir(),'acr-'));const seeds=[opportunity('seed-a'),opportunity('seed-b'),opportunity('seed-c')];let discoveries=0,proposals=0;const g={chat:async(_p,p)=>{if(p==='discover'){discoveries++;return{content:JSON.stringify({opportunities:[opportunity('same','New title'),{...opportunity('other','New title'),id:'other',slug:'other',source:'discovered'},{...opportunity('third','Third'),source:'discovered'}]}),usage:{total_tokens:1}}}return p==='proposal'?{content:JSON.stringify(pkg('pkg-'+(++proposals))),usage:{total_tokens:1}}:{content:'{"decision":"PASS","reasons":[]}',usage:{total_tokens:1}}}};for(let i=0;i<3;i++)assert.equal((await runBoundedCycle(cfg(d),g,seeds)).status,'candidate_saved');assert.equal((await runBoundedCycle(cfg(d),g,seeds)).status,'candidate_saved');assert.equal(discoveries,1);assert.equal(status(cfg(d)).totalDiscoveredOpportunities,2);assert.equal((await runBoundedCycle(cfg(d),g,seeds)).status,'candidate_saved');assert.equal(readdirSync(join(d,'packages')).length>=2,true)});
test('identical package hash returns duplicate without second index record',async()=>{const d=mkdtempSync(join(tmpdir(),'acr-'));const seeds=[opportunity('a'),opportunity('b')];assert.equal((await runBoundedCycle(cfg(d),gateway('same'),seeds)).status,'candidate_saved');assert.equal((await runBoundedCycle(cfg(d),gateway('same'),seeds)).status,'duplicate');assert.equal(readFileSync(join(d,'candidates.jsonl'),'utf8').split('\n').filter(Boolean).length,1)});
test('budget admission, lock, circuit and materialization permissions',async()=>{const d=mkdtempSync(join(tmpdir(),'acr-'));assert.equal((await runBoundedCycle(cfg(d,{dailyTokenBudget:9999}),gateway(),[opportunity('a')])).status,'budget_exhausted');const release=acquireLock(d);assert.throws(()=>acquireLock(d),/busy/);release();const d2=mkdtempSync(join(tmpdir(),'acr-'));const bad={chat:async()=>{throw new GatewayError('transient_503')}};for(let i=0;i<3;i++)assert.equal((await runBoundedCycle(cfg(d2),bad,[opportunity('a')])).status,'transient_failure');assert.equal((await runBoundedCycle(cfg(d2),bad,[opportunity('a')])).status,'cooldown')});


test('high-value curated seeds are unique and valid',()=>{
  const expected=['erp-read-first-investigator','postgresql-report-query-reviewer','api-contract-reviewer','webhook-delivery-debugger','erp-data-lineage-tracer'];
  assert.equal(CURATED_SEEDS.length,8);
  assert.deepEqual(expected.filter(id=>!CURATED_SEEDS.some(x=>x.id===id)),[]);
  assert.equal(CURATED_SEEDS.every(validateOpportunity),true);
  assert.equal(new Set(CURATED_SEEDS.map(x=>x.id)).size,CURATED_SEEDS.length);
  assert.equal(new Set(CURATED_SEEDS.map(x=>x.slug)).size,CURATED_SEEDS.length);
  assert.equal(new Set(CURATED_SEEDS.map(x=>x.title.trim().toLowerCase())).size,CURATED_SEEDS.length);
});
test('curated reconciliation appends missing seeds once to non-empty state',()=>{
  const d=mkdtempSync(join(tmpdir(),'acr-'));
  const existing=opportunity('existing');
  writeFileSync(join(d,'opportunities.jsonl'),JSON.stringify(existing)+'\n');
  const first=reconcileCuratedSeeds(d,CURATED_SEEDS), second=reconcileCuratedSeeds(d,CURATED_SEEDS);
  assert.equal(first.length,CURATED_SEEDS.length);
  assert.equal(second.length,0);
  const rows=readFileSync(join(d,'opportunities.jsonl'),'utf8').split('\n').filter(Boolean).map(JSON.parse);
  assert.equal(rows.length,1+CURATED_SEEDS.length);
  assert.equal(rows[0].id,'existing');
});
test('bounded cycle reconciles new curated seeds before discovery',async()=>{
  const d=mkdtempSync(join(tmpdir(),'acr-'));
  writeFileSync(join(d,'opportunities.jsonl'),JSON.stringify({...opportunity('old'),source:'curated'})+'\n');
  writeFileSync(join(d,'cycles.jsonl'),Array.from({length:MAX_GENERATION_ATTEMPTS},()=>JSON.stringify({opportunityId:'old',outcome:'unsafe_candidate'})).join('\n')+'\n');
  const g=gateway('new-cap');
  const r=await runBoundedCycle(cfg(d),g,[opportunity('old'),opportunity('new-curated')]);
  assert.equal(r.opportunityId,'new-curated');
  assert.equal(r.status,'candidate_saved');
  assert.equal(reconcileCuratedSeeds(d,[opportunity('old'),opportunity('new-curated')]).length,0);
});

test('malformed proposal retries bounded times then consumes',async()=>{const d=mkdtempSync(join(tmpdir(),'acr-'));const bad={chat:async(_p,p)=>p==='discover'?{content:'{"opportunities":[]}',usage:{total_tokens:1}}:{content:'not-json',usage:{total_tokens:1}}};for(let i=0;i<MAX_GENERATION_ATTEMPTS;i++)assert.equal((await runBoundedCycle(cfg(d),bad,[opportunity('one')])).status,'malformed_json');assert.equal((await runBoundedCycle(cfg(d),bad,[opportunity('one')])).status,'discovery_empty');});
