import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DemoGateway, GatewayError, runBoundedCycle, status, validateCandidate, validateReview, acquireLock } from '../packages/factory/dist/index.js';
const cfg=(d,e={})=>({baseUrl:'https://gateway.test/demo',origin:'https://origin.test',projectId:'github-pages',model:'demo-auto',dailyTokenBudget:1000000,minRemainingForCall:10000,stateDir:d,...e});
const response=(s,b)=>new Response(JSON.stringify(b),{status:s,headers:{'content-type':'application/json'}});
test('gateway contract and one 401 refresh',async()=>{const calls=[];let sessions=0;const secret='do-not-log-token';const fetcher=async(url,init)=>{calls.push({url,init});if(url.endsWith('/session')){sessions++;assert.deepEqual(Object.keys(JSON.parse(init.body)),['project_id']);return response(200,{dmo_token:secret})}if(sessions===1)return response(401,{});assert.deepEqual(Object.keys(JSON.parse(init.body)).sort(),['messages','model','stream']);assert.equal(JSON.parse(init.body).stream,false);assert.equal(JSON.parse(init.body).purpose,undefined);return response(200,{choices:[{message:{content:'{"decision":"PASS","reasons":[]}'}}],usage:{prompt_tokens:3,completion_tokens:4,total_tokens:7}})};const g=new DemoGateway(cfg('/tmp/unused'),fetcher);const r=await g.chat('x','review');assert.equal(r.usage.total_tokens,7);assert.equal(sessions,2);assert.equal(calls[0].init.headers.Origin,'https://origin.test');assert.equal(calls.at(-1).init.headers.Origin,'https://origin.test');assert.equal(JSON.stringify(r).includes(secret),false)});
test('offline cycle captures usage and saves candidate only',async()=>{const d=mkdtempSync(join(tmpdir(),'acr-factory-'));let n=0;const g={chat:async(_p,p)=>{n++;return p==='proposal'?{content:'{"name":"safe-cap","description":"read only","permissions":{"network":false,"filesystem":false},"files":["README.md"]}',usage:{total_tokens:12}}:{content:'{"decision":"PASS","reasons":[]}',usage:{total_tokens:8}}}};const r=await runBoundedCycle(cfg(d),g,[{id:'one',title:'one',request:'one'}]);assert.equal(r.status,'candidate_saved');assert.equal(n,2);assert.ok(readdirSync(d).some(x=>x.endsWith('.json')));const l=readFileSync(join(d,'budget.jsonl'),'utf8');assert.match(l,/"total_tokens":12/);assert.match(l,/"total_tokens":8/);assert.equal(l.includes('Bearer'),false);assert.equal(status(cfg(d)).latestCycle.outcome,'candidate_saved')});
test('unsafe proposal, reviewer fail, and budget skip are clean',async()=>{const base={id:'one',title:'one',request:'one'};const d=mkdtempSync(join(tmpdir(),'acr-factory-'));const bad={chat:async()=>({content:'{"name":"bad","description":"x","commands":["rm -rf"]}',usage:{total_tokens:1}})};assert.equal((await runBoundedCycle(cfg(d),bad,[base])).status,'unsafe_candidate');const d2=mkdtempSync(join(tmpdir(),'acr-factory-'));const fail={chat:async(_p,p)=>({content:p==='proposal'?'{"name":"ok","description":"x","permissions":{"network":false,"filesystem":false},"files":["README.md"]}':'{"decision":"FAIL","reasons":["x"]}',usage:{total_tokens:1}})};assert.equal((await runBoundedCycle(cfg(d2),fail,[base])).status,'review_failed');const d3=mkdtempSync(join(tmpdir(),'acr-factory-'));assert.equal((await runBoundedCycle(cfg(d3,{dailyTokenBudget:9999}),fail,[base])).status,'budget_exhausted')});

test('candidate and review validators fail closed adversarially',()=>{const base={name:'safe-cap',description:'x',permissions:{network:false,filesystem:false},files:['README.md']};for(const bad of [{...base,script:'x'},{...base,unknown:true},{...base,files:['x.sh']},{...base,files:['../README.md']},{...base,permissions:{network:false,filesystem:false,unknown:false}},{...base,permissions:{network:true,filesystem:false}},{...base,files:['README.md','README.md']}])assert.equal(validateCandidate(bad),false);assert.equal(validateCandidate(base),true);assert.equal(validateReview({decision:'PASS',reasons:[],extra:false}),false);assert.equal(validateReview({decision:'PASS',reasons:Array(21).fill('x')}),false)});

test('stale dead lock is recovered but live or malformed lock is busy',()=>{const d=mkdtempSync(join(tmpdir(),'acr-lock-'));const release=acquireLock(d);assert.throws(()=>acquireLock(d),/busy/);release();writeFileSync(join(d,'.lock'),JSON.stringify({pid:999999,createdAt:new Date().toISOString()}));const recovered=acquireLock(d);recovered();writeFileSync(join(d,'.lock'),'not-json');assert.throws(()=>acquireLock(d),/busy/)})

test('three transient failures cool down and success resets the streak',async()=>{const d=mkdtempSync(join(tmpdir(),'acr-circuit-'));let calls=0;const failing={chat:async()=>{calls++;throw new GatewayError('transient_503')}};const seed=[{id:'one',title:'one',request:'one'}];for(let i=0;i<3;i++)assert.equal((await runBoundedCycle(cfg(d),failing,seed)).status,'transient_failure');assert.equal(calls,3);assert.equal((await runBoundedCycle(cfg(d),failing,seed)).status,'cooldown');assert.equal(calls,3)});
test('status uses Singapore calendar day',()=>{const d=mkdtempSync(join(tmpdir(),'acr-factory-'));const s=status(cfg(d));assert.equal(s.remainingTokens,1000000);assert.equal(s.day,new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()))});
test('429 and 403 map to clean gateway outcomes',async()=>{for(const code of [429,403]){const g=new DemoGateway(cfg('/tmp/unused'),async()=>response(code,{}));await assert.rejects(()=>g.chat('x','proposal'),new RegExp(code===429?'rate_limited':'configuration_blocked'))}});
