import test from 'node:test';
import assert from 'node:assert/strict';
import {appendFileSync,mkdirSync,mkdtempSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {buildContextBundle,createFactoryCatalog,LocalCatalog,loadFactoryCatalog,resolveCapability} from '../packages/registry-api/dist/index.js';

const canonical=x=>Array.isArray(x)?`[${x.map(canonical).join(',')}]`:x&&typeof x==='object'?`{${Object.keys(x).sort().map(k=>`${JSON.stringify(k)}:${canonical(x[k])}`).join(',')}}`:JSON.stringify(x);
const hash=x=>createHash('sha256').update(canonical(x)).digest('hex');
const candidate=(name='postgres-query-reviewer',o={})=>({schema:'acr/candidate-package/v0.1',name,version:'0.1.0',description:'Review PostgreSQL query JSON safely.',category:'sql-analysis',tags:['postgresql','query'],permissions:{network:false,filesystem:false,database:false,shell:false},files:[{path:'README.md',content:'# Safe package'},{path:'evals/cases.json',content:'[{"id":"basic"}]'}],...o});
function add(state,pkg=candidate(),o={}){const packageHash=hash(pkg),opportunityId=o.opportunityId??`${pkg.name}-op`,createdAt=o.createdAt??'2026-09-17T00:00:00.000Z',path=o.path??join(state,'packages',pkg.name,packageHash);mkdirSync(path,{recursive:true});const wrapper={schema:'acr/candidate-package/v0.1',status:o.wrapperStatus??'CANDIDATE_ONLY',opportunityId,packageHash,createdAt,package:pkg};writeFileSync(join(path,'manifest.json'),JSON.stringify(wrapper));const record={opportunityId,name:o.recordName??pkg.name,packageHash:o.recordHash??packageHash,path,status:o.recordStatus??'CANDIDATE_ONLY',createdAt};appendFileSync(join(state,'candidates.jsonl'),JSON.stringify(record)+'\n');return{record,wrapper,path}}
const entry=(name,o={})=>({name,version:o.version??'0.1.0',description:o.description??'none',category:o.category??'documentation',tags:o.tags??[],status:o.status??'CANDIDATE_ONLY',path:o.path??`/x/${name}/${o.version??'0.1.0'}`,packageHash:'a'.repeat(64),opportunityId:`${name}-op`,createdAt:'2026-09-17T00:00:00.000Z',source:'factory'});

test('registry ranking is exact name > name prefix > tag > category > description and all query tokens must match',()=>{const c=new LocalCatalog([entry('description-match',{description:'alpha reference'}),entry('category-match',{category:'alpha'}),entry('tag-match',{tags:['alpha']}),entry('alpha-tool'),entry('alpha')]);assert.deepEqual(c.search('alpha').map(x=>x.name),['alpha','alpha-tool','tag-match','category-match','description-match']);const multi=new LocalCatalog([entry('alpha-beta'),entry('alpha-only'),entry('beta-only')]);assert.deepEqual(multi.search('alpha beta').map(x=>x.name),['alpha-beta'])});

test('registry empty query ordering, filters, limits and info version selection are deterministic',()=>{const c=new LocalCatalog([entry('zeta'),entry('alpha',{version:'1.2.0',category:'sql-analysis'}),entry('alpha',{version:'1.10.0',category:'sql-analysis'}),entry('alpha',{version:'not-semver'}),entry('beta',{status:'REVIEWED'})]);assert.deepEqual(c.search('',{limit:3}).map(x=>`${x.name}@${x.version}`),['alpha@1.10.0','alpha@1.2.0','alpha@not-semver']);assert.deepEqual(c.search('',{category:'sql-analysis'}).map(x=>x.name),['alpha','alpha']);assert.deepEqual(c.search('',{status:'REVIEWED'}).map(x=>x.name),['beta']);assert.equal(c.info('alpha').version,'1.10.0');assert.equal(c.info('alpha','1.2.0').version,'1.2.0');assert.throws(()=>c.search('',{limit:0}),/1 to 100/);assert.throws(()=>c.search('',{limit:101}),/1 to 100/)});

test('factory loader accepts only indexed matching candidate manifests inside packages root',()=>{const state=mkdtempSync(join(tmpdir(),'acr-registry-'));mkdirSync(join(state,'packages'),{recursive:true});writeFileSync(join(state,'candidates.jsonl'),'');const good=add(state,candidate('good-cap'));appendFileSync(join(state,'candidates.jsonl'),JSON.stringify(good.record)+'\n');appendFileSync(join(state,'candidates.jsonl'),'{bad json\n');appendFileSync(join(state,'candidates.jsonl'),JSON.stringify({...good.record,name:'wrong-name'})+'\n');appendFileSync(join(state,'candidates.jsonl'),JSON.stringify({...good.record,packageHash:'b'.repeat(64)})+'\n');appendFileSync(join(state,'candidates.jsonl'),JSON.stringify({...good.record,status:'REJECTED'})+'\n');const missing={...good.record,name:'missing',opportunityId:'missing-op',packageHash:'c'.repeat(64),path:join(state,'packages','missing','c'.repeat(64))};appendFileSync(join(state,'candidates.jsonl'),JSON.stringify(missing)+'\n');const outside=mkdtempSync(join(tmpdir(),'acr-outside-'));const outsideRecord={...good.record,name:'outside',opportunityId:'outside-op',path:outside};appendFileSync(join(state,'candidates.jsonl'),JSON.stringify(outsideRecord)+'\n');const entries=loadFactoryCatalog(state);assert.equal(entries.length,1);assert.equal(entries[0].name,'good-cap');assert.equal(entries[0].packageHash,good.record.packageHash);assert.equal(entries[0].path,resolve(good.path))});

test('factory loader rejects malformed manifest shapes and non-candidate wrapper status',()=>{const state=mkdtempSync(join(tmpdir(),'acr-registry-'));mkdirSync(join(state,'packages'),{recursive:true});writeFileSync(join(state,'candidates.jsonl'),'');const nonCandidate=add(state,candidate('not-candidate'),{wrapperStatus:'REVIEWED'});const bad=add(state,candidate('bad-shape'));const wrapper=JSON.parse(readFileSync(join(bad.path,'manifest.json'),'utf8'));wrapper.package.permissions.shell=true;writeFileSync(join(bad.path,'manifest.json'),JSON.stringify(wrapper));assert.deepEqual(loadFactoryCatalog(state),[]);assert.equal(nonCandidate.wrapper.status,'REVIEWED')});

test('cap search and cap info work from foreign cwd with bounded flag validation',()=>{const state=mkdtempSync(join(tmpdir(),'acr-registry-cli-'));mkdirSync(join(state,'packages'),{recursive:true});writeFileSync(join(state,'candidates.jsonl'),'');add(state,candidate('postgres-json-inspector',{category:'json-analysis',tags:['postgresql','json'],description:'Inspect postgres JSON output.'}));const foreign=mkdtempSync(join(tmpdir(),'acr-foreign-')),cli=resolve('packages/cli/dist/index.js');const run=args=>spawnSync(process.execPath,[cli,...args],{cwd:foreign,encoding:'utf8'});let r=run(['search','postgres','--state-dir',state]);assert.equal(r.status,0,r.stderr);let body=JSON.parse(r.stdout);assert.equal(body.status,'PASS');assert.equal(body.count,1);assert.equal(body.results[0].name,'postgres-json-inspector');r=run(['info','postgres-json-inspector','--state-dir',state]);assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).result.name,'postgres-json-inspector');for(const args of [['search','postgres','--limit','0','--state-dir',state],['search','postgres','--limit','101','--state-dir',state],['search','postgres','--wat','x'],['info','missing','--state-dir',state]]){r=run(args);assert.notEqual(r.status,0);assert.equal(JSON.parse(r.stderr).status,'FAIL')}});

test('resolver performs search info select deterministically and reports no match',()=>{const c=new LocalCatalog([entry('json-helper',{tags:['json']}),entry('postgres-json',{tags:['postgresql','json'],description:'postgres json'})]);const r=resolveCapability(c,'postgres json',{limit:5});assert.equal(r.selected.name,'postgres-json');assert.deepEqual(r.stages.map(x=>x.stage),['search','info','select']);assert.equal(r.selection.strategy,'deterministic-search-rank');const none=resolveCapability(c,'missing-token');assert.equal(none.selected,null);assert.equal(none.stages[0].status,'NO_MATCH')});

test('context use bundle is bounded context-only and revalidates selected evidence',()=>{const state=mkdtempSync(join(tmpdir(),'acr-use-'));mkdirSync(join(state,'packages'),{recursive:true});writeFileSync(join(state,'candidates.jsonl'),'');const longReadme='# Guide\n'+('é'.repeat(3000));const pkg=candidate('context-cap',{description:'postgres context helper',tags:['postgresql'],files:[{path:'README.md',content:longReadme},{path:'evals/cases.json',content:'[{"id":"basic"}]'}]});const added=add(state,pkg);const resolution=resolveCapability(createFactoryCatalog(state),'postgres');const bundle=buildContextBundle(resolution,{maxBytes:2048});assert.equal(bundle.mode,'context-only');assert.equal(bundle.executable,false);assert.equal(bundle.status,'CANDIDATE_ONLY');assert.equal(bundle.selected.name,'context-cap');assert.ok(bundle.totalBytes<=2048);assert.equal(bundle.truncated,true);assert.ok(bundle.files.every(f=>f.path.endsWith('.md')||f.path.endsWith('.json')));const wrapper=JSON.parse(readFileSync(join(added.path,'manifest.json'),'utf8'));wrapper.package.description='tampered';writeFileSync(join(added.path,'manifest.json'),JSON.stringify(wrapper));assert.throws(()=>buildContextBundle(resolution,{maxBytes:2048}),/no longer matches registry evidence/)});

test('cap resolve and cap use expose automatic context-only workflow from foreign cwd',()=>{const state=mkdtempSync(join(tmpdir(),'acr-resolve-cli-'));mkdirSync(join(state,'packages'),{recursive:true});writeFileSync(join(state,'candidates.jsonl'),'');add(state,candidate('postgres-agent-helper',{tags:['postgresql','agent'],description:'Help an agent review postgres query output.'}));const foreign=mkdtempSync(join(tmpdir(),'acr-foreign-')),cli=resolve('packages/cli/dist/index.js');const run=args=>spawnSync(process.execPath,[cli,...args],{cwd:foreign,encoding:'utf8'});let r=run(['resolve','postgres agent','--state-dir',state]);assert.equal(r.status,0,r.stderr);let body=JSON.parse(r.stdout);assert.equal(body.status,'PASS');assert.equal(body.result.selected.name,'postgres-agent-helper');assert.deepEqual(body.result.stages.map(x=>x.stage),['search','info','select']);r=run(['use','postgres agent','--max-bytes','2048','--state-dir',state]);assert.equal(r.status,0,r.stderr);body=JSON.parse(r.stdout);assert.equal(body.bundle.mode,'context-only');assert.equal(body.bundle.executable,false);assert.ok(body.bundle.totalBytes<=2048);r=run(['use','nothing-matches','--state-dir',state]);assert.equal(r.status,2);assert.equal(JSON.parse(r.stdout).status,'NO_MATCH');r=run(['use','postgres','--max-bytes','10','--state-dir',state]);assert.notEqual(r.status,0);assert.equal(JSON.parse(r.stderr).status,'FAIL')});
