import { appendFileSync, existsSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync, openSync, closeSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';

export interface ProviderAdapter { discover(query: string): Promise<string[]>; candidate(item: string): Promise<string> }
export interface DailyBudget { dailyTokens: number; usedTokens: number; resetAt: string }
export type GateStatus = 'PASS'|'FAIL'|'UNKNOWN';
export type FactoryStage = 'Discover'|'Candidate'|'Validate'|'Eval'|'Security Gate'|'Candidate Release';
export interface FactoryRun { stages: FactoryStage[]; budget: DailyBudget; gateStatuses?: Partial<Record<'Validate'|'Eval'|'Security Gate'|'Candidate Release', GateStatus>> }
export interface FactoryGates { validate(candidate:string):Promise<GateStatus>; evaluate(candidate:string):Promise<GateStatus>; security(candidate:string):Promise<GateStatus>; release(candidate:string):Promise<GateStatus> }
export async function runFactory(provider:ProviderAdapter,query:string,budget:DailyBudget,gates?:FactoryGates):Promise<FactoryRun>{const stages:FactoryStage[]=[];const statuses:FactoryRun['gateStatuses']={};const items=await provider.discover(query);stages.push('Discover');if(!items.length)return {stages,budget,gateStatuses:statuses};const candidate=await provider.candidate(items[0]);stages.push('Candidate');if(!gates)return {stages,budget,gateStatuses:statuses};for(const [stage,key,fn] of [['Validate','Validate',gates.validate],['Eval','Eval',gates.evaluate],['Security Gate','Security Gate',gates.security],['Candidate Release','Candidate Release',gates.release]] as const){const status=await fn(candidate);statuses[key as keyof typeof statuses]=status;stages.push(stage as FactoryStage);if(status!=='PASS')break}return {stages,budget,gateStatuses:statuses}}

export const DEFAULTS = Object.freeze({baseUrl:'https://gpt.yapweijun1996.com/demo',origin:'https://aiagent-sg-2026.github.io',projectId:'github-pages',model:'demo-auto',dailyTokenBudget:1_000_000,minRemainingForCall:10_000,stateDir:'/srv/agent-workstation/state/agent-capability-registry-factory',timezone:'Asia/Singapore'});
export interface FactoryConfig { baseUrl:string; origin:string; projectId:string; model:string; dailyTokenBudget:number; minRemainingForCall:number; stateDir:string }
export function configFromEnv(env:NodeJS.ProcessEnv=process.env):FactoryConfig{return {baseUrl:env.ACR_FACTORY_BASE_URL||DEFAULTS.baseUrl,origin:env.ACR_FACTORY_ORIGIN||DEFAULTS.origin,projectId:env.ACR_FACTORY_PROJECT_ID||DEFAULTS.projectId,model:env.ACR_FACTORY_MODEL||DEFAULTS.model,dailyTokenBudget:num(env.ACR_FACTORY_DAILY_TOKEN_BUDGET,DEFAULTS.dailyTokenBudget),minRemainingForCall:num(env.ACR_FACTORY_MIN_REMAINING_FOR_CALL,DEFAULTS.minRemainingForCall),stateDir:env.ACR_FACTORY_STATE_DIR||DEFAULTS.stateDir}}
function num(v:string|undefined,f:number):number{const n=Number(v);return Number.isFinite(n)&&n>=0?n:f}
export interface FetchLike{(input:string|URL,init?:RequestInit):Promise<Response>}
export interface Usage{prompt_tokens?:number;completion_tokens?:number;total_tokens:number}
export interface Gateway{chat(prompt:string,purpose:'proposal'|'review'):Promise<{content:string;usage:Usage}>}
export interface CycleResult{status:'candidate_saved'|'no_seed'|'budget_exhausted'|'cooldown'|'rate_limited'|'configuration_blocked'|'transient_failure'|'review_failed'|'malformed_json'|'unsafe_candidate'|'duplicate'|'busy'|'error';cycleAt:string;candidatePath?:string;reason?:string;seedId?:string}
interface Circuit{transientStreak:number;cooldownUntil?:string;lastOutcome?:string}
export interface Seed{id:string;title:string;request:string}
export const CURATED_SEEDS:Seed[]=[{id:'postgresql-query-reviewer',title:'PostgreSQL query reviewer',request:'A safe, deterministic reviewer for PostgreSQL query risks.'},{id:'http-json-inspector',title:'HTTP JSON inspector',request:'A read-only capability that inspects JSON responses without network side effects.'},{id:'markdown-link-checker',title:'Markdown link checker',request:'A bounded checker that reports malformed local markdown links.'}];
export class GatewayError extends Error{constructor(public readonly outcome:string){super(outcome)}}
export class DemoGateway implements Gateway{private token?:string;private tokenAt=0;constructor(private readonly c:FactoryConfig,private readonly fetcher:FetchLike=globalThis.fetch.bind(globalThis)){}
 private async session():Promise<void>{const r=await this.fetcher(`${this.c.baseUrl}/session`,{method:'POST',headers:{Origin:this.c.origin,'content-type':'application/json'},body:JSON.stringify({project_id:this.c.projectId})});if(r.status===403)throw new GatewayError('configuration_blocked');if(!r.ok)throw new GatewayError(r.status===429?'rate_limited':`transient_${r.status}`);const j:any=await r.json();const t=[j.token,j.access_token,j.demo_token,j.dmo_token,j.session_token].find((v:any)=>typeof v==='string'&&v.length>0);if(typeof t!=='string')throw new GatewayError('configuration_blocked');this.token=t;this.tokenAt=Date.now()}
 async chat(prompt:string,_purpose:'proposal'|'review'):Promise<{content:string;usage:Usage}>{let refreshed=false;for(;;){if(!this.token||Date.now()-this.tokenAt>800000)await this.session();const r=await this.fetcher(`${this.c.baseUrl}/v1/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${this.token!}`,Origin:this.c.origin,'content-type':'application/json'},body:JSON.stringify({model:this.c.model,messages:[{role:'user',content:prompt}],stream:false})});if(r.status===401&&!refreshed){this.token=undefined;refreshed=true;continue}if(r.status===401||r.status===403)throw new GatewayError('configuration_blocked');if(r.status===429)throw new GatewayError('rate_limited');if(r.status>=500)throw new GatewayError(`transient_${r.status}`);if(!r.ok)throw new GatewayError(`error_${r.status}`);const j:any=await r.json();const content=j.choices?.[0]?.message?.content,u=j.usage;if(typeof content!=='string'||!u||typeof u.total_tokens!=='number')throw new GatewayError('malformed_gateway_response');return {content,usage:{prompt_tokens:u.prompt_tokens,completion_tokens:u.completion_tokens,total_tokens:u.total_tokens}}}}
}
function sgDay(now=new Date()):string{return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(now)}function iso(){return new Date().toISOString()}function ensure(d:string){mkdirSync(d,{recursive:true,mode:0o700})}function atomic(p:string,v:string){const t=`${p}.${process.pid}.tmp`;writeFileSync(t,v,{mode:0o600});renameSync(t,p)}
function jsonFile<T>(p:string,f:T):T{try{return JSON.parse(readFileSync(p,'utf8')) as T}catch{return f}}
function parse(s:string):unknown{const t=s.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');return JSON.parse(t)}
const PERMISSIONS=['network','filesystem','database','shell'] as const;
export function validateCandidate(x:unknown):boolean{if(!x||typeof x!=='object'||Array.isArray(x)||![Object.prototype,null].includes(Object.getPrototypeOf(x)))return false;const o=x as any;if(Object.keys(o).some(k=>!['name','description','permissions','files'].includes(k))||Object.keys(o).length!==4)return false;if(typeof o.name!=='string'||!/^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/.test(o.name))return false;if(typeof o.description!=='string'||o.description.length===0||o.description.length>2000)return false;if(!o.permissions||typeof o.permissions!=='object'||Array.isArray(o.permissions)||![Object.prototype,null].includes(Object.getPrototypeOf(o.permissions))||Object.keys(o.permissions).some(k=>!(PERMISSIONS as readonly string[]).includes(k)||o.permissions[k]!==false)||o.permissions.network!==false||o.permissions.filesystem!==false)return false;if(!Array.isArray(o.files)||o.files.length===0||o.files.length>32||new Set(o.files).size!==o.files.length)return false;return o.files.every((p:any)=>typeof p==='string'&&p.length<=200&&p.length>0&&!p.includes('\\')&&!p.startsWith('/')&&!/^[A-Za-z]:/.test(p)&&!p.split('/').some((part:string)=>part===''||part==='.'||part==='..')&&/\.(md|json)$/.test(p))}
export function validateReview(x:unknown):boolean{if(!x||typeof x!=='object'||Array.isArray(x))return false;const o=x as any;return Object.keys(o).length===2&&Object.keys(o).every(k=>k==='decision'||k==='reasons')&&(o.decision==='PASS'||o.decision==='FAIL')&&Array.isArray(o.reasons)&&o.reasons.length<=20&&o.reasons.every((r:any)=>typeof r==='string')}
function prompt(s:Seed){return `Return only strict JSON. Propose one data-only capability for seed ${s.id}. Request: ${s.request}. Shape: {"name":"kebab-name","description":"...","permissions":{"network":false,"filesystem":false},"files":["README.md"]}. No code, commands, hooks, installation, network, secrets, or package fetching.`}function reviewPrompt(x:unknown){return `Return only strict JSON {"decision":"PASS"|"FAIL","reasons":["..."]}. Review this candidate against: data-only markdown/json; no executable content, commands, hooks, network, fetching, secrets, path traversal, or elevated permissions. Candidate: ${JSON.stringify(x)}`}
function ledger(c:FactoryConfig){return join(c.stateDir,'budget.jsonl')}function cycles(c:FactoryConfig){return join(c.stateDir,'cycles.jsonl')}function used(c:FactoryConfig,day=sgDay()){if(!existsSync(ledger(c)))return 0;return readFileSync(ledger(c),'utf8').split('\n').filter(Boolean).reduce((n,l)=>{try{const x=JSON.parse(l);return x.day===day?n+Number(x.total_tokens||0):n}catch{return n}},0)}function record(c:FactoryConfig,purpose:string,u:Usage){appendFileSync(ledger(c),JSON.stringify({day:sgDay(),timestamp:iso(),model:c.model,purpose,prompt_tokens:u.prompt_tokens,completion_tokens:u.completion_tokens,total_tokens:u.total_tokens})+'\n',{mode:0o600})}
function update(c:FactoryConfig,outcome:string,transient:boolean){const p=join(c.stateDir,'circuit.json'),o=jsonFile<Circuit>(p,{transientStreak:0}),st=transient?o.transientStreak+1:0;atomic(p,JSON.stringify({transientStreak:st,lastOutcome:outcome,...(st>=3?{cooldownUntil:new Date(Date.now()+7200000).toISOString()}: {})}))}
export function acquireLock(d:string):()=>void{const p=join(d,'.lock');try{const fd=openSync(p,'wx',0o600);writeFileSync(fd,JSON.stringify({pid:process.pid,createdAt:iso()}));closeSync(fd);return()=>{try{unlinkSync(p)}catch{}}}catch{try{const x=JSON.parse(readFileSync(p,'utf8'));if(!Number.isInteger(x.pid)||typeof x.createdAt!=='string')throw new Error();try{process.kill(x.pid,0)}catch(e:any){if(e.code==='ESRCH'){unlinkSync(p);return acquireLock(d)}}}catch{}throw new Error('busy')}}
function appendCycle(c:FactoryConfig,r:CycleResult){const outcome=r.status==='configuration_blocked'?'config_blocked':r.status==='transient_failure'?'transient':r.status==='malformed_json'?'malformed':r.status==='unsafe_candidate'?'unsafe':r.status;appendFileSync(cycles(c),JSON.stringify({seedId:r.seedId??null,outcome,timestamp:r.cycleAt,tokenTotals:{used:used(c),remaining:Math.max(0,c.dailyTokenBudget-used(c))},...(r.reason?{reason:r.reason}: {})})+'\n',{mode:0o600})}
export async function runBoundedCycle(c:FactoryConfig=configFromEnv(),g:Gateway=new DemoGateway(c),seeds:Seed[]=CURATED_SEEDS):Promise<CycleResult>{ensure(c.stateDir);const cycleAt=iso();let release:()=>void;try{release=acquireLock(c.stateDir)}catch{return {status:'busy',cycleAt}}let seedId:string|undefined;const finish=(r:CycleResult)=>{appendCycle(c,{...r,cycleAt,seedId});return r};try{const cir=jsonFile<Circuit>(join(c.stateDir,'circuit.json'),{transientStreak:0});if(cir.cooldownUntil&&Date.now()<Date.parse(cir.cooldownUntil))return finish({status:'cooldown',cycleAt,reason:'cooldown'});if(c.dailyTokenBudget-used(c)<c.minRemainingForCall)return finish({status:'budget_exhausted',cycleAt,reason:'admission budget'});const cp=join(c.stateDir,'candidates.jsonl');const seen=new Set(readFileSync(cp,{encoding:'utf8',flag:'a+'}).split('\n').filter(Boolean).map(l=>{try{return JSON.parse(l).seedId}catch{return ''}}));const seed=seeds.find(s=>!seen.has(s.id));if(!seed)return finish({status:'no_seed',cycleAt});seedId=seed.id;let p;try{p=await g.chat(prompt(seed),'proposal');record(c,'proposal',p.usage);update(c,'model_success',false)}catch(e){return finish(fail(c,cycleAt,e))}let candidate;try{candidate=parse(p.content)}catch{return finish(done(c,cycleAt,'malformed_json'))}if(!validateCandidate(candidate))return finish(done(c,cycleAt,'unsafe_candidate'));if(c.dailyTokenBudget-used(c)<c.minRemainingForCall)return finish({status:'budget_exhausted',cycleAt,reason:'review admission budget'});let rv;try{rv=await g.chat(reviewPrompt(candidate),'review');record(c,'review',rv.usage);update(c,'model_success',false)}catch(e){return finish(fail(c,cycleAt,e))}let r:unknown;try{r=parse(rv.content)}catch{return finish(done(c,cycleAt,'malformed_json'))}if(!validateReview(r))return finish(done(c,cycleAt,'malformed_json'));if((r as any).decision!=='PASS')return finish(done(c,cycleAt,'review_failed'));const h=createHash('sha256').update(canonical(candidate)).digest('hex'),path=join(c.stateDir,`candidate-${seed.id}-${h}.json`);atomic(path,JSON.stringify({status:'CANDIDATE_ONLY',seedId:seed.id,createdAt:cycleAt,candidate},null,2)+'\n');appendFileSync(cp,JSON.stringify({seedId:seed.id,path,status:'CANDIDATE_ONLY',createdAt:cycleAt})+'\n');update(c,'candidate_saved',false);return finish({status:'candidate_saved',cycleAt,candidatePath:path})}finally{release!()}}
function canonical(x:any):string{if(Array.isArray(x))return `[${x.map(canonical).join(',')}]`;if(x&&typeof x==='object')return `{${Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')}}`;return JSON.stringify(x)}
function done(c:FactoryConfig,at:string,s:CycleResult['status']):CycleResult{update(c,s,false);return {status:s,cycleAt:at}}function fail(c:FactoryConfig,at:string,e:unknown):CycleResult{const o=e instanceof GatewayError?e.outcome:'transient_network',t=o.startsWith('transient')||o==='transient_network';update(c,o,t);const s=o==='rate_limited'||o==='configuration_blocked'?o:t?'transient_failure':'error';return {status:s as CycleResult['status'],cycleAt:at,reason:o}}
export function status(c:FactoryConfig=configFromEnv()){ensure(c.stateDir);const d=sgDay(),u=used(c,d),line=readFileSync(cycles(c),{encoding:'utf8',flag:'a+'}).trim().split('\n').filter(Boolean).slice(-1)[0]||null;return {status:'PASS',day:d,usedTokens:u,dailyTokenBudget:c.dailyTokenBudget,remainingTokens:Math.max(0,c.dailyTokenBudget-u),minRemainingForCall:c.minRemainingForCall,circuit:jsonFile<Circuit>(join(c.stateDir,'circuit.json'),{transientStreak:0}),latestCycle:line?JSON.parse(line):null}}
